package com.dennis.bookora.navigation

object BookoraDestinations {
    const val Welcome = "welcome"
    const val Login = "login"
    const val Register = "register"
    const val ForgotPassword = "forgot_password"
    const val Main = "main"
    const val Home = "home"
    const val Search = "search"
    const val Create = "create"
    const val Favorites = "favorites"
    const val Profile = "profile"
    const val BookDetails = "book_details"
    const val Messages = "messages"
    const val EditProfile = "edit_profile"
    const val MyListings = "my_listings"
    const val EditListing = "edit_listing"
    const val Settings = "settings"
    const val About = "about"
    const val Privacy = "privacy"
    const val Terms = "terms"
    const val Notifications = "notifications"
    const val NotificationDetails = "notification_details"
    const val Chat = "chat"

    fun bookDetails(bookId: String) = "book_details/$bookId"
    const val BookDetailsPattern = "book_details/{bookId}"
    fun notificationDetails(notificationId: String) = "notification_details/$notificationId"
    const val NotificationDetailsPattern = "notification_details/{notificationId}"
    fun editListing(bookId: String) = "edit_listing/$bookId"
    const val EditListingPattern = "edit_listing/{bookId}"
    fun chat(conversationId: String) = "chat/$conversationId"
    const val ChatPattern = "chat/{conversationId}"
}
